#### 배열 만들기

In [1]:
# 리스트에서 배열 만들기
import numpy as np
a = np.array([1, 4, 2, 5, 3])
b = np.array([3.14, 4, 2, 3])
c = np.array([1, 2, 3, 4], dtype = float)
print(a, b, c)

[1 4 2 5 3] [3.14 4.   2.   3.  ] [1. 2. 3. 4.]


In [2]:
a

array([1, 4, 2, 5, 3])

In [3]:
b

array([3.14, 4.  , 2.  , 3.  ])

In [4]:
c

array([1., 2., 3., 4.])

In [2]:
# 함수를 이용하여 배열 만들기
a = np.zeros(10, dtype = int) # 0으로 채운 배열 생성
b = np.ones((3, 5), dtype = float) #1로 채운 배열 생성
c = np.full((3,5), 3.14) # 3.14로 채운 배열 만들기 
d = np.arange(0, 20, 2) # 0에서 시작해 2씩 더해 20까지 채우는 배열 생성
e = np.linspace(0, 1, 5) # 0과 1 사이에 일정한 간격을 가진 다섯 개의 값으로 채운 배열 만들기
f = np.random.random((3,3)) # 3*3 크기의 난수 배열 생성
g = np.random.normal(0, 1, (3, 3)) # 평균 0, 표준 편차 1의 정규 분포를 따르는 3*3 난수 배열
h = np.random.randint(0, 10, (3, 3)) # [0, 10) 구간의 임의로 정수로 채운 3*3 배열 만들기
i = np.eye(3) # 크기 3의 단위 행렬 만들기

print("np.zeros(10, dtype = int):\n", a)
print("\nnp.ones((3, 5), dtype = float):\n", b)
print("\nnp.full((3,5), 3.14):\n", c)
print("\nnp.arange(0, 20, 2):\n", d)
print("\nnp.linspace(0, 1, 5):\n", e)
print("\nnp.random.random((3,3)):\n", f)
print("\nnp.random.normal(0, 1, (3, 3)):\n", g)
print("\nnp.random.randint(0, 10, (3, 3)):\n", h)
print("\nnp.eye(3):\n", i)

np.zeros(10, dtype = int):
 [0 0 0 0 0 0 0 0 0 0]

np.ones((3, 5), dtype = float):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

np.full((3,5), 3.14):
 [[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]

np.arange(0, 20, 2):
 [ 0  2  4  6  8 10 12 14 16 18]

np.linspace(0, 1, 5):
 [0.   0.25 0.5  0.75 1.  ]

np.random.random((3,3)):
 [[0.18262827 0.27692481 0.69023281]
 [0.55079247 0.28145341 0.07734313]
 [0.63129821 0.39951056 0.36086524]]

np.random.normal(0, 1, (3, 3)):
 [[ 2.00213728 -0.22744782  0.07246514]
 [-1.49533855  0.2893585   0.35447377]
 [ 0.52527444 -1.6999584  -0.22105502]]

np.random.randint(0, 10, (3, 3)):
 [[4 1 8]
 [5 3 1]
 [0 1 9]]

np.eye(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 인덱싱과 슬라이싱

In [5]:
# 기본적인 인덱싱과 슬라이싱
x1 = np.array([1, 3, 5, 7, 9])

print("x1[0]:", x1[0]) # 양수 인덱스 (맨 앞 요소)
print("x1[3]:", x1[3]) # 세 번째 요소 
print("x1[-1]:", x1[-1]) # 음수 인덱스 (맨 뒤 요소)
print("x1[-2]:", x1[-2]) # 뒤에서 네 번째 요소 

print("x1[1:3]:", x1[1:3]) # 1번째 요소부터 3번째 요소까지 슬라이싱

x1[0]: 1
x1[3]: 7
x1[-1]: 9
x1[-2]: 7
x1[1:3]: [3 5]


In [8]:
x2

array([[0.95993715, 0.89384616, 0.86637042, 0.74422476, 0.2076551 ],
       [0.90450119, 0.09896062, 0.5980032 , 0.72525142, 0.37142647],
       [0.82978847, 0.40735121, 0.02646538, 0.64321665, 0.6424685 ],
       [0.15657183, 0.89127111, 0.9024431 , 0.82924352, 0.50654717],
       [0.91795215, 0.34967258, 0.44742199, 0.69074884, 0.54005106],
       [0.57210752, 0.46614885, 0.94497135, 0.03666224, 0.15319774],
       [0.44669552, 0.96712778, 0.33405666, 0.87628173, 0.59547695],
       [0.9266934 , 0.67006163, 0.06378979, 0.79796435, 0.92641776],
       [0.07485477, 0.14514047, 0.37148092, 0.36692883, 0.98838882],
       [0.88598766, 0.14705731, 0.15832775, 0.20842547, 0.0775289 ]])

In [10]:
# 2차원 배열의 인덱싱 및 슬라이싱
x2 = np.random.random(size = (10, 5))

print("x2[0, 1]", x2[0, 1])
print("x2[1:4, 2]\n", x2[1:4, 2])
print("x2[0, 2:4]\n", x2[0, 2:4])
print("x2[0:3, 2:4]\n", x2[0:3, 2:4])

x2[0, 1] 0.3597326025238873
x2[1:4, 2]
 [0.77363942 0.94615221 0.15664472]
x2[0, 2:4]
 [0.53831925 0.16621449]
x2[0:3, 2:4]
 [[0.53831925 0.16621449]
 [0.77363942 0.25632754]
 [0.94615221 0.6300682 ]]


#### 유니버설 함수

In [21]:
# 사용 기초
x = np.array([1, 2, 3, 4])
y = np.array([4, 3, 2, 1])

print("x + y = ", x + y)
print("x - y = ", x - y)
print("x * y = ", x * y)
print("x / y = ", x / y)
print("log x = ", np.log(x))

x + y =  [5 5 5 5]
x - y =  [-3 -1  1  3]
x * y =  [4 6 6 4]
x / y =  [0.25       0.66666667 1.5        4.        ]
log x =  [0.         0.69314718 1.09861229 1.38629436]


In [22]:
# 루프와 유니버설 함수의 속도 비교
arr_1 = np.random.randint(1, 10, size = 10 ** 8)
arr_2 = np.random.randint(1, 10, size = 10 ** 8)
import time
### 리스트를 사용하여 벡터의 덧셈 구현
t1 = time.time()
output = []
for val1, val2 in zip(arr_1, arr_2):
    output.append(val1 + val2)
t2 = time.time()
print("반복문을 사용한 경우:", round(t2 - t1, 4))

### 유니버설 함수를 사용하여 벡터의 덧셈 구현
t1 = time.time()
output = arr_1 + arr_2
t2 = time.time()
print("유니버설 함수를 사용한 경우:", round(t2 - t1, 4))

반복문을 사용한 경우: 45.9652
유니버설 함수를 사용한 경우: 6.4692


In [11]:
# 브로드캐스팅
print("np.arange(3) + 5:", 
      np.arange(3) + 5, '\n')

print("np.ones((3, 3)) + np.arange(3)\n",
      np.ones((3, 3)) + np.arange(3), '\n')

print("np.arange(3).reshape(3, 1) + np.arange(3)\n",
      np.arange(3).reshape(3, 1) + np.arange(3))

np.arange(3) + 5: [5 6 7] 

np.ones((3, 3)) + np.arange(3)
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]] 

np.arange(3).reshape(3, 1) + np.arange(3)
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


In [24]:
# 브로드캐스팅 예시: z - normalization
X = np.random.random((10, 3))
Xmean = X.mean(axis = 0) # 열별 평균 크기: (1, 3)
Xstd = X.std(axis = 0) # 열별 표준편차 크기: (1, 3)

Z = (X - Xmean) / Xstd

print("X:", X)
print("\nXmean:\n", Xmean)
print("\nXstd:\n", Xstd)
print("\nZ:\n", Z)

X: [[0.45128136 0.60071565 0.40055875]
 [0.03452332 0.01519741 0.03614602]
 [0.11699555 0.54947815 0.64927445]
 [0.53262962 0.61794848 0.90591084]
 [0.03022641 0.27088968 0.38840134]
 [0.06164409 0.85463811 0.29485522]
 [0.21194227 0.78073511 0.95192774]
 [0.11392525 0.35561173 0.82914594]
 [0.81957851 0.74591089 0.0353037 ]
 [0.19980402 0.79578455 0.44312513]]

Xmean:
 [0.25725504 0.55869098 0.49346491]

Xstd:
 [0.24792542 0.25553305 0.31590509]

Z:
 [[ 0.78259954  0.16445886 -0.29409517]
 [-0.89838194 -2.12690127 -1.4476465 ]
 [-0.5657326  -0.03605337  0.49321629]
 [ 1.1107154   0.23189763  1.30560076]
 [-0.91571341 -1.12627817 -0.33257954]
 [-0.78899111  1.158156   -0.62870053]
 [-0.18276775  0.86894489  1.45126762]
 [-0.57811656 -0.79472793  1.0626009 ]
 [ 2.26811542  0.73266417 -1.45031285]
 [-0.23172701  0.9278392  -0.15935096]]


#### 비교 연산자

In [12]:
L = np.array([1, 2, 3, 4, 5])
L >= 3

array([False, False,  True,  True,  True])

In [27]:
# 비교 연산자
L = np.array([1, 2, 3, 4, 5])
cond = L >= 3
sum(cond) # 조건을 만족하는 요소의 개수

3

In [28]:
L[cond] # 조건을 만족하는 요소만 반환

array([3, 4, 5])