In [10]:
import pandas as pd
import numpy as np
from factor_analyzer import FactorAnalyzer
from factor_analyzer.factor_analyzer import calculate_bartlett_sphericity, calculate_kmo

In [2]:
df = pd.read_csv('final_animal_visit_travel.csv', encoding = 'cp949')

In [3]:
df

시군구      방문자 수  관광명소  기타   숙박  음식점  카페   A10   A11   A12
0    가평군   22105529    13  11  223   35  37  4.17  3.95  3.99
1    강남구  103309405     2  11    3   10  36  4.10  4.13  3.98
2    강동구   23706460     2   6    1    2  18  3.60  3.92  3.96
3    강릉시   26260986     8  11   70   33  33  4.27  4.13  3.75
4    강북구   18328235     1   5    1    6  19  4.50  4.00  3.89
..   ...        ...   ...  ..  ...  ...  ..   ...   ...   ...
224  홍천군   15071693     5   5   69    6   8  4.26  4.15  4.08
225  화성시   51736786    13  25   24    9  66  4.19  4.02  3.98
226  화순군    7963778     4   4    4    2   8  4.41  4.16  3.97
227  화천군    2428709     3   2   11    0   0  4.00  4.23  4.11
228  횡성군    8176074     2   0   31    2   4  4.08  4.24  4.13

[229 rows x 10 columns]

In [5]:
df[df['시군구'] == '울릉군']

시군구    방문자 수  관광명소  기타  숙박  음식점  카페   A10   A11   A12
153  울릉군  1511584     5   3   3    3   3  4.44  4.23  4.06

In [7]:
df2 = df[df['시군구'] != '성북구']

In [8]:
df3 = df2.drop('시군구', axis=1).values

In [11]:
df4 = (df3 - np.mean(df3, axis = 0))/np.std(df3, axis = 0, ddof =True)

In [12]:
df4

array([[ 0.23132006,  1.72801058,  0.55670931, ...,  0.01779381,
        -0.25042905,  0.10360073],
       [ 5.17085507, -0.40478988,  0.55670931, ..., -0.20065947,
         0.28766562,  0.07500392],
       [ 0.32870279, -0.40478988, -0.18731017, ..., -1.76104007,
        -0.3401115 ,  0.0178103 ],
       ...,
       [-0.6289058 , -0.01700798, -0.48491795, ...,  0.7667765 ,
         0.37734807,  0.04640711],
       [-0.96559745, -0.21089893, -0.78252574, ..., -0.51273559,
         0.58660711,  0.44676248],
       [-0.61599209, -0.40478988, -1.08013353, ..., -0.26307469,
         0.61650125,  0.5039561 ]])

In [13]:
_, p_value = calculate_bartlett_sphericity(df4)
_, kmo_measure = calculate_kmo(df4)

In [14]:
p_value, kmo_measure

(0.0, 0.7211440934492269)

In [17]:
fa = FactorAnalyzer(n_factors=2, rotation = 'varimax').fit(df4)

In [18]:
fa.loadings_

array([[ 0.639366  ,  0.01494298],
       [ 0.66051183,  0.00747946],
       [ 0.85602814,  0.00959182],
       [ 0.49745732,  0.01962431],
       [ 0.89464742, -0.02819708],
       [ 0.81633548, -0.00638244],
       [ 0.07456736,  0.71254429],
       [ 0.08290657,  0.96520989],
       [ 0.10495262,  0.94182079]])

In [19]:
fa.transform(df4)

array([[ 2.35807710e+00, -3.43395245e-01],
       [ 6.68887683e-01,  2.65252120e-02],
       [-2.92821407e-01, -2.87427140e-01],
       [ 2.12411871e+00, -1.76525201e-01],
       [-1.43350115e-01, -1.04082360e-01],
       [ 5.93495289e-01,  6.38857100e-03],
       [-5.60896566e-01,  1.31419411e+00],
       [-5.90488761e-01,  1.01876251e-01],
       [ 3.58753609e-01,  1.71157254e-01],
       [-7.48831239e-01,  7.92213748e-01],
       [-6.60459503e-01,  4.35467312e-01],
       [-1.92701816e-01, -3.73785527e-01],
       [ 2.26477008e+00, -1.69089854e-01],
       [-7.89621394e-01, -2.83446915e+00],
       [-9.06431201e-01, -2.49431398e-01],
       [ 3.80357507e+00, -9.08793191e-01],
       [-4.91941755e-01, -3.83349214e+00],
       [-7.19399518e-01, -1.90332437e-01],
       [-7.99009815e-01, -9.13792739e-01],
       [-5.06124723e-02, -1.15599412e-01],
       [-7.47758008e-01,  2.80352251e-01],
       [-4.25381268e-01, -2.17322306e-01],
       [-1.06547833e-01, -1.56091085e-01],
       [-5.